name: Print Environment Variables
on: ["push"]

jobs:
  github-variables:
    runs-on: ubuntu-latest
    steps:
      - name: commit id
        run: echo $GITHUB_SHA
      - name: user and repo name
        run: echo $GITHUB_REPOSITORY
      - name: the GITHUb object
        run: echo "${{ GITHUB.token }}"
