name: set up R
on: ["push"]

jobs:
  set-up-r:
    runs-on: ubuntu-20.04
    steps:
      - name: setup R and install ggplot2
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.1" # The R version to download (if necessary) and use.
        run: |
          Rscript -e 'install.packages("ggplot2")'
  library-ggplot2:
    runs-on: windows-latest
    needs: ["set-up-r"]
    steps:
      - name: library ggplot2
        run: Rscript -e 'library(ggplot2)'
