name: set up R
on: ["push"]

jobs:
  set-up-r:
    runs-on: ubuntu-20.04
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.1" # The R version to download (if necessary) and use.
      - run: |
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'library(ggplot2)'
