name: Shell Commands
on: [push]

jobs:
  run-shell-commend:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "a meb ssage from Github Actions"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
